# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name_plural': 'Ürünler'},
        ),
    ]
