# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0005_auto_20171112_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='user',
        ),
        migrations.DeleteModel(
            name='Urun',
        ),
    ]
