# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Urun', '0006_auto_20171113_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=30)),
                ('urun_stok', models.IntegerField(default=0, max_length=5)),
                ('urun_ktarihi', models.DateTimeField(auto_now=True)),
                ('urun_fiyati', models.FloatField(default=0.0)),
                ('urun_aciklama', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satici', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
