# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0007_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urun_stok',
            field=models.IntegerField(default=0),
        ),
    ]
