# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:51
from __future__ import unicode_literals

import Profil.storage
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0008_auto_20171113_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_resmi',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=Profil.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
