# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0009_urun_urun_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='slug',
            field=models.SlugField(default='slugiyy', unique=True),
            preserve_default=False,
        ),
    ]
