# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0010_urun_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='slug',
            field=models.SlugField(),
        ),
    ]
