# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0011_auto_20171118_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='slug',
        ),
    ]
