# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urun', '0012_remove_urun_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_slug',
            field=models.SlugField(default='xd', unique=True),
            preserve_default=False,
        ),
    ]
