# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Uyelik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_tipi', models.CharField(choices=[('MS', 'Müşteri'), ('ST', 'Satıcı')], default='MS', help_text='Lütfen üye tipinizi seçiniz.', max_length=2, verbose_name='Üye Tipi')),
                ('adres', models.CharField(default='', help_text='Lütfen bir adres yazın.', max_length=100, verbose_name='Adres')),
                ('dogum_tarihi', models.DateField(blank=True, help_text='Doğum Tarihi', verbose_name='Doğum Tarihiniz.')),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='uyelik',
            name='kullanici',
        ),
        migrations.DeleteModel(
            name='Uyelik',
        ),
    ]
