# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uyelik', '0002_auto_20171022_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adres',
            field=models.TextField(default='', help_text='Lütfen bir adres yazın.', max_length=100, verbose_name='Adres'),
        ),
    ]
