# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uyelik', '0004_auto_20171022_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='adres',
            field=models.TextField(blank=True, help_text='Lütfen bir adres yazın.', max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dogum_tarihi',
            field=models.DateField(blank=True, help_text='Doğum Tarihi', null=True, verbose_name='Doğum Tarihiniz.'),
        ),
    ]
