# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uyelik', '0005_auto_20171023_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dogum_tarihi',
            field=models.DateField(blank=True, help_text='Doğum Tarihi', null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
