# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uyelik', '0009_myuser_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profil_foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar Seçin'),
        ),
    ]
