# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:44
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Uyelik', '0012_auto_20171029_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profil_foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
    ]
